<TextInput>:
    font_size: '16dp'
    font_name: './res/fonts/Geologica-Regular.ttf'
    background_color: 0, 0, 0, 1
    foreground_color: 1, 1, 1, 1
    disabled_foreground_color: 1, 1, 1, 0.3
    cursor_color: 1, 1, 1, 1
    hint_text_color: 1, 1, 1, .7
    padding: 10
    size_hint_y: None
    canvas.before:
        Line:
            width: 1
            rounded_rectangle: (self.x, self.y, self.width, self.height, 5)